server:
  port: 3045

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: mini-decoder-test
    password: mypassdecoder
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
